---
- name: Aplicação do Install
  hosts: hosts_cisco
  gather_facts: no
  ignore_errors: yes
  
  tasks:
  - iosxr_command:
      commands: "install activate id {{ id }} "
    register: install 