---
- name: Checagem dos pacotes
  hosts: hosts_cisco
  gather_facts: no
  ignore_errors: yes
  
  tasks:
  - iosxr_command:
      commands: "admin sh install ac summ "
    register: installed
  - debug: var=installed.stdout_lines