---
- name: commit pacote
  hosts: hosts_cisco
  gather_facts: no
  ignore_errors: yes
  
  tasks:
  - iosxr_command:
      commands: "install commit"
    register: commit
  - debug: var=commit.stdout_lines